backend:
  name: github
  repo: muneo992/my-nuxt-app # リポジトリのパス (例: "your-username/your-repo")
  branch: main # 使用するブランチ
  auth_scope: repo # 必要なスコープを指定 (デフォルトは "repo" スコープ)

site_url: https://nuxt253.netlify.app # Netlify サイトの URL
logo_url: https://nuxt253.netlify.app/images/logo.png # ロゴ画像の URL (任意)

media_folder: "static/images/uploads" # アップロードされた画像の保存先
public_folder: "/images/uploads" # 公開 URL パス

collections:
  - name: "cars"
    label: "Cars"
    folder: "content/cars"
    format: 'frontmatter' 
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "year", label: "Year", widget: "number" }
      - { name: "mileage", label: "Mileage", widget: "number" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "markdown" }
